name: Validate & Publish Plugin
on:
  pull_request:
    paths:
      - "plugins/**"
      - "schemas/**"
  push:
    branches: [main]
    paths:
      - "plugins/**"

permissions:
  contents: write
  id-token: write

jobs:
  build-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with: { node-version: "20" }

      - name: Install deps
        run: npm ci
        # package.json should include ajv, ajv-formats, semver, cyclonedx/cdxgen or anchore/syft, cosign, minisign

      - name: Validate plugin manifests
        run: node scripts/validate-plugin.mjs

      - name: Generate SBOMs for changed bundles
        run: |
          npx @cyclonedx/cdxgen -o sbom.json -t javascript -r .
          # or: syft packages dir:plugins -o cyclonedx-json > sbom.json

      - name: Sign new/updated bundles (cosign keyless)
        run: |
          for f in $(git diff --name-only HEAD~1 | grep "plugins/.*/bundle/index.esm.js" || true); do
            cosign sign-blob --yes $f > "$f.sig"
          done

      - name: Update registry
        run: node scripts/update-registry.mjs

      - name: Sign registry
        run: node scripts/sign.mjs registry/index.json registry/index.json.sig

      - name: Commit changes
        run: |
          git config user.name "fabric-bot"
          git config user.email "bot@fabric"
          git add registry/index.json registry/index.json.sig plugins/**/bundle/index.esm.js.sig plugins/**/bundle/sbom.json
          git commit -m "chore: publish plugins" || echo "No changes"
          git push
